### //agregar producto
POST http://localhost:9000/api/productos HTTP/1.1
Content-Type: application/json

{
    "sku": 348,
    "producto": "Leche de Almendras 1100 mL",
    "descripcion": "Bolsa de leche de Almendras por 1100 mL",
    "valor": 7000
}

### //listar productos
GET http://localhost:9000/api/productos HTTP/1.1

### //buscar producto
GET http://localhost:9000/api/productos/6173ad3b2253c8b4ce9ea17e HTTP/1.1

### //editar productos
PUT http://localhost:9000/api/productos/6173ad3b2253c8b4ce9ea17e HTTP/1.1
Content-Type: application/json

{
    "sku": 346,
    "producto": "Leche de deslactosada 1100 mL",
    "descripcion": "Bolsa de leche deslactosada por 1100 mL",
    "valor": 4000
}

### //eliminar producto
DELETE http://localhost:9000/api/productos/6173acd32253c8b4ce9ea17c HTTP/1.1

